version: '3.8'

services:
  postgres:
    image: postgres:10
    container_name: my_postgres_container2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shadowXhunter
      POSTGRES_PASSWORD: Rabi123
      POSTGRES_DB: chatapp
    volumes:
      - my_postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  app:
    build:
      context: ./  # Path to the Dockerfile directory
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env

volumes:
  my_postgres_data: