version: '3.8'

services:
  postgres:
    image: postgres:10
    container_name: my_postgres_container2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chatapp
    volumes:
      - my_postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:latest
    container_name: my_redis_container
    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    
    
    

volumes:
  my_postgres_data: