name: Docker Image Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_publish:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        with:
            node-version: '20'  # Explicitly set Node.js version
        run: |
          cd backend
          docker login --username rabindra-sss --password ${{secrets.GH_TOKEN}}
          docker build . --tag ghcr.io/rabindra-sss/chat-app-image:latest
          docker push ghcr.io/rabindra-sss/chat-app-image:latest